### ISSUE TITLE
Third discord link

### ISSUE THREAD

**Issue by BanThoncc** [mathmakgakpak/owopppa#6]
I don't know if i'm banned from the server but the third discord link doesn't work
![discord_3.png](https://owoppa.netlify.com/img/discord_3.png "The third discord link in help tab")

**Comment by BanThoncc** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>***

**Comment by BanThoncc** [comment]
@mathias377 fix when idk

**Comment by BanThoncc** [comment]
>***
***

**Comment by mathmakgakpak** [comment]
Idk

**Comment by mathmakgakpak** [comment]
When i want

**Comment by mathmakgakpak** [comment]
Repaired :D
